app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_session import Session
from werkzeug.security import generate_password_hash, check_password_hash
import sqlite3

from .helpers import apology, login_required, lookup, usd


main_bp = Blueprint('main', __name__)

# SQLite database file
database_file = 'books.db'
user_database_file = 'users.db'

# Configure session to use filesystem (you can choose other options)
main_bp.config = {}
main_bp.config['SESSION_PERMANENT'] = False
main_bp.config['SESSION_TYPE'] = 'filesystem'
Session(main_bp)

@main_bp.after_request
def after_request(response):
    """Ensure responses aren't cached"""
    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
    response.headers["Expires"] = 0
    response.headers["Pragma"] = "no-cache"
    return response

@main_bp.route('/')
def index():
    if request.method == 'GET':
        conn = sqlite3.connect(database_file)
        cursor = conn.cursor()

        cursor.execute('''
            SELECT
                title,
                authors,
                average_rating
            FROM books
            ORDER BY publication_date DESC LIMIT 50
        ''')
        
        books = cursor.fetchall()

        conn.close()

        return render_template('index.html', books=books)
    

@main_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        # Retrieve form data
        username = request.form.get('first_name')
        email = request.form.get('email')
        password = request.form.get('pwd')
        password_confirm = request.form.get('pwd-2')

        # Validate form data (add your validation logic)
        if not username:
            return apology("must provide username", 400)

        # Ensure password was submitted
        elif not password:
            return apology("must provide password", 400)

        if password != password_confirm:
            return apology("passwords do not match", 400)

        # Connect to the database and create a cursor
        conn = sqlite3.connect(user_database_file)
        db = conn.cursor()

        # Query database for username
        user_rows = db.execute("SELECT * FROM users WHERE username = ?", (username,))

        # Ensure username does not exist
        if len(list(user_rows)):
            return apology("username in use, please select another", 400)

        # Generate hashed password and insert the new user
        hash_password = generate_password_hash(
            password, method="pbkdf2:sha256", salt_length=8
        )
        db.execute(
            "INSERT INTO users (username, email, password_hash) VALUES (?, ?, ?)", (username, email, hash_password)
        )

        # Commit changes and close the connection
        conn.commit()
        conn.close()

        # Remember which user has logged in and redirect to home page
        # Query database for username
        conn = sqlite3.connect(user_database_file)
        db = conn.cursor()
        user = db.execute(
            "SELECT * FROM users WHERE username = ?", (request.form.get("first_name"),)
        ).fetchone()

        session["user_id"] = user[0]

        return apology("Registered successfully", 200)
    else:
        return render_template("signup.html")



@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('pwd')

        # Connect to the SQLite users database
        conn = sqlite3.connect(user_database_file)
        cursor = conn.cursor()

        # Retrieve user information based on the provided username
        cursor.execute('''
            SELECT id, username, password_hash FROM users WHERE username = ?
        ''', (username,))

        user = cursor.fetchone()

        if user and check_password_hash(user[2], password):
            # If the username and password are correct, set up the user session
            session['user_id'] = user[0]
            flash('Login successful!', 'success')
            # Close the database connection
            conn.close()
            return redirect(url_for('main.index'))
        else:
            # Close the database connection
            conn.close()
            # Flash an error message if login fails
            return apology('Login not successful', 400)


    return render_template('login.html')

@main_bp.route('/logout')
@login_required
def logout():
    # Clear the user session
    session.clear()
    flash('Logout successful!', 'success')
    return redirect(url_for('main.index'))

def get_book_info(book_name):
    conn = sqlite3.connect(database_file)
    cursor = conn.cursor()

    cursor.execute('''
        SELECT
            book_id,
            title,
            authors,
            average_rating,
            language_code,
            num_pages,
            ratings_count,
            publication_date,
            publisher
        FROM books
        WHERE title = ?
    ''', (book_name,))

    detailed_book_info = cursor.fetchone()

    conn.close()

    return detailed_book_info

@main_bp.route('/list_book', methods=['GET', 'POST'])
@login_required
def list_book():
    # Handle listing books logic
    if request.method == 'POST':
        title = request.form.get('title')
        author = request.form.get('author')
        description = request.form.get('description')
        state = request.form.get('state')
        rating = request.form.get('rating')
        num_pages = request.form.get('num_pages')
        publication_date = request.form.get('publication_date')
        publisher = request.form.get('publisher')

        if not title:
            return apology('please enter a valid title', 400)
        elif not author:
            return apology('please enter a valid author(s)', 400)
        
        conn = sqlite3.connect(database_file)
        cursor = conn.cursor()

        cursor.execute('''
            INSERT INTO books (title, authors, average_rating, language_code, num_pages, ratings_count, publication_date, publisher)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ''', (title, author, rating, 'en', num_pages, 1, publication_date, publisher))
        
        conn.commit()
        conn.close()
        
        book = get_book_info(title)
        return render_template('book_details.html', book=book)

    else:
        return render_template('listbook.html')
        

@main_bp.route('/book/<book_name>', methods=['GET'])
def book_details(book_name):
    # Fetch detailed book information
    print(book_name)
    book = get_book_info(book_name)

    if book:
        return render_template('book_details.html', book=book)
    else:
        # Handle the case where the book is not found
        return render_template('error.html', message='Book not found'), 404

@main_bp.route('/add_to_my_books/<int:book_id>', methods=['POST'])
@login_required
def add_to_my_books(book_id):
    if request.method == 'POST':
        # Get the user_id from the session
        user_id = session['user_id']

        # Connect to the SQLite users database
        conn = sqlite3.connect(user_database_file)
        cursor = conn.cursor()

        # Add the book to the user's collection
        cursor.execute("INSERT INTO user_books (user_id, book_id) VALUES (?, ?)", (user_id, book_id))
        conn.commit()
        flash('Book added to your collection successfully', 'success')

        # Close the database connection
        conn.close()

        return redirect(url_for('main.my_books'))

@main_bp.route('/my_books', methods=['GET'])
@login_required
def my_books():
    # Get the user_id from the session
    user_id = session['user_id']

    # Connect to the SQLite users database
    conn_users = sqlite3.connect(user_database_file)
    cursor_users = conn_users.cursor()

    # Fetch book IDs for the user
    cursor_users.execute('''
        SELECT book_id FROM user_books WHERE user_id = ?
    ''', (user_id,))

    book_ids = cursor_users.fetchall()

    # Close the connection to the users database
    conn_users.close()

    # Connect to the SQLite books database
    conn_books = sqlite3.connect(database_file)
    cursor_books = conn_books.cursor()

    # Fetch book details based on book IDs
    user_books = []
    for book_id in book_ids:
        cursor_books.execute('''
            SELECT book_id, title, authors, average_rating, language_code, num_pages, ratings_count, publication_date, publisher
            FROM books
            WHERE book_id = ?
        ''', (book_id[0],))
        book_details = cursor_books.fetchone()
        user_books.append(book_details)

    # Close the connection to the books database
    conn_books.close()    
    return render_template('mybooks.html', user_books=user_books)

@main_bp.route('/remove_book/<int:book_id>', methods=['POST'])
@login_required
def remove_book(book_id):
    # Get the user_id from the session
    user_id = session['user_id']

    # Connect to the SQLite users database
    conn = sqlite3.connect(user_database_file)
    cursor = conn.cursor()

    # Remove the book from the user's books
    cursor.execute("DELETE FROM user_books WHERE user_id = ? AND book_id = ?", (user_id, book_id))
    conn.commit()
    flash('Book removed from your collection successfully', 'success')

    # Close the database connection
    conn.close()

    return redirect(url_for('main.my_books'))

app/templates/apology.html
{% extends "layout.html" %}

{% block content %}
    <!-- https://memegen.link/ -->
    <img alt="{{ top }}" class="border img-fluid" src="http://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
    <a class="btm-submit-btn" href="{{ url_for('main.login') }}">Go back to homepage</a>
{% endblock %}

app/templates/book_details.html
{% extends 'layout.html' %}

{% block content %}
  <div class="container add-padding" id="book-details">
    <h2><span>{{ book[1] }}</span></h2>
    <p id="book-d-author"><span>Author:</span> {{ book[2] }}</p>
    <p id="book-d-genre"><span>Average Rating:</span> {{ book[3] }}</p>
    <p><span>Language:</span> {{ book[4] }}</p>
    <p><span>Number of Pages:</span> {{ book[5] }}</p>
    <p><span>Ratings Count:</span> {{ book[6] }}</p>
    <p><span>Publication Date:</span> {{ book[7] }}</p>
    <p><span>Publisher:</span> {{ book[8] }}</p>
    
    <form id="book-details-btn" method="POST" action="{{ url_for('main.add_to_my_books', book_id=book[0]) }}" style="background-color: transparent;">
      <button class="book-list-btn btn" type="submit">Add to My Books</button>
    </form>
  </div>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
  <!-- Intro Section -->
  <section class="intro" id="intro-2"> 
    <div class="container split-layout">
      <div class="left-half">
          <h1>Sign Up and Start Trading Your Favorite Books</h1>
          <p>One reader's treasure is another reader's delight, and with our platform, you can easily trade and discover new books to add to your personal library.</p>
          <a class="top-submit-btn btn" href="">Sign up now</a>
      </div>
      <div class="right-half">
        <div id="search">
          <form id="search-bar" method="GET" action="{{ url_for('main.index') }}">
              <p>Search for desired book below by either entering book name or the author name.</p>
              <label for="book-name">Title: </label>
              <input type="text" id="book-name" class="book-name" style="width: 50;" />
              <label for="author">Author: </label>
              <input type="text" id="book-auth" class="book-auth" style="width:50" />
              <input type="submit" id="search-btn btn" value="Search" />
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block available_books %}
  <div class="container add-padding">
    <h2 class="centered-h2">Available Books</h2>
    <p id="intro-text" style="text-align:center;">Find a selection of available book listings available for trade.</p>

    <ul id="book-list">
        {% for book in books %}
            <li>
                <h3 id="book-d-title">{{ book[0] }}</h3>
                <p id="book-d-author">Author: {{ book[1] }}</p>
                <p id="book-d-genre">Score: {{ book[2] }}</p>
                <a class="book-list-btn btn" href="{{ url_for('main.book_details', book_name=book[0]) }}">View Book</a>
            </li>
        {% endfor %}
    </ul>
  </div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BookXchange</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- Bootstrap JS and Popper.js (required for Bootstrap dropdowns and modals) -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <!--Local JS-->
    <script src="{{ url_for('static', filename='js/form.js') }}"></script>

    <!--Local CSS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">

    <!--Favicon-->
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon/favicon_transparent.ico') }}">
</head>

<body>
    <!-- Navigation Bar -->
    <div class="container">
        <nav class="navbar navbar-expand-lg">
            <!-- Logo on the left -->
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img id="logo" src="{{ url_for('static', filename='images/logo-nobackground.png') }}" alt="Logo">
            </a>

            <!-- Navigation Links on the right -->
            <div class="navbar-collapse justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.list_book') }}">Add a Book</a></li>
                                        
                    {% if session['user_id'] %}
                        <!-- If user is logged in, show logout button -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.my_books') }}">My Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                        </li>
                    {% else %}
                        <!-- If user is not logged in, show signup/login links -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                Sign up/Login
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('main.signup') }}">Create a new account</a>
                                <a class="dropdown-item" href="{{ url_for('main.login') }}">Login</a>
                                <a class="dropdown-item" href="{{ url_for('main.my_books') }}">My Books</a>
                            </div>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </nav>
    </div>


    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <div class="container">
        {% block available_books %}{% endblock %}
    </div>

    <div id="error-message"></div>

</body>

</html>

app/templates/listbook.html
{% extends 'layout.html'%}

{% block content %}
    <form id="post-form" action="/list_book" method="POST">
        <h2 class="centered-h2">Post a Book Listing</h2>
        <label for="title-input">Title:</label><br>
        <input type="text" id="title-input" name="title"><br>
        <label for="author-input">Author:</label><br>
        <input type="text" id="author-input" name="author"><br>
        <label for="description-input">Description:</label><br>
        <textarea id="description-input" name="description"></textarea><br>
        <label for="state">Please select the option which matches most:</label> <br>
        <select id="state" name="state">
          <option value="new">New</option>
          <option value="like_new">Used, in new condition</option>
          <option value="good">Used, in good condition</option>
          <option value="fair">Used, in fair condition</option>
          <option value="poor">Used, in poor condition</option>
        </select><br><br>
        <label for="rating">Average rating of the book</label><br>
        <input type="number" id="rating-input" name="rating"><br>
        <label for="num_pages">Number of pages:</label><br>
        <input type="number" id="num_pages_input" name="num_pages"><br>
        <label for="publication_date">Publication Date of the book:</label><br>
        <input type="date" id="publication_date_input" name="publication_date"><br>
        <label for="publisher">Publisher:</label><br>
        <input type="text" id="publisher-input" name="publisher"><br>
        <input type="submit" id="post-listing" value="Post Listing">
      </form> 
      
{% endblock %}

app/templates/login.html
{% extends 'layout.html'%}

{% block content %}
<main>
    <section class="intro"> <!-- Intro Section -->
        <h1>Login to Your Account</h1>
        <p><span>Sign in to access your BookXchange account and start exploring a world of books. If you don't have an account, you can <a href="{{ url_for('main.signup') }}">sign up here</a>.</span></p>
    </section>

    <section> <!-- Login Section-->
        <form id="form-full" action="/login" method="POST">
            <div class="input-form">
                <h1 id="signup-title">Login Here!</h1>

                <div>
                    <input class="fname-field" type="username" name="username" placeholder="Username" required>
                    <p class="email-error-message email-success-message txt"></p>
                </div>

                <div>
                    <input class="pwd-field" type="password" name="pwd" placeholder="Password" required>
                    <p class="pwd-error-message pwd-success-message txt"></p>
                </div>

                <div>
                    <button class="btm-submit-btn" type="submit">Login</button>
                </div>

                <p>Don't have an account yet? <a href="{{ url_for('main.signup') }}">Sign up here</a></p>
            </div>
        </form>
    </section>
</main>

{% endblock %}

app/templates/mybooks.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container add-padding">
        <h1>My Books</h1>

        {% if user_books %}
            <ul class="my-books-list">
                {% for book in user_books %}
                    <li>
                        <a href="{{ url_for('main.book_details', book_name=book[1]) }}">
                            <span id="book-d-title">{{ book[1] }}</span> <span id="book-d-author">by {{ book[2] }}</span>
                        </a>
                        <form id="remove-form" method="POST" action="{{ url_for('main.remove_book', book_id=book[0]) }}" style="background-color: transparent; display: inline;">
                            <button type="submit" class="book-list-btn btn" id="remove_button">Remove</button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No books in your collection yet.</p>
        {% endif %}
    </div>
{% endblock %}

app/templates/signup.html
{% extends 'layout.html' %}

{% block content %}
<main>
    <section class="intro"> <!-- Intro Section -->
        <h1>Sign Up for BookXchange</h1>
        <p>Join our community of book lovers. Sign up and start trading your favorite books with others.</p>
    </section>

    <section> <!-- Sign Up Section-->
        <form id="form-full" action="/signup" method="POST">
            <div class="input-form">
                <h1 id="signup-title">Sign Up Here!</h1>

                <div>
                    <label for="username">Username:</label>
                    <input class="fname-field" id="username" type="text" name="username" placeholder="Username" required>
                    <p class="fname-error-message fname-success-message txt"></p>
                </div>

                <div>
                    <label for="email">Email:</label>
                    <input class="email-field" id="email" type="email" name="email" placeholder="Email Address" required>
                    <p class="email-error-message email-success-message txt"></p>
                </div>

                <div>
                    <label for="pwd-field">Password:</label>
                    <input class="pwd-field" id="pwd-field" type="password" name="pwd" placeholder="Password" required>
                    <p class="pwd-error-message pwd-success-message txt"></p>
                </div>

                <div>
                    <label for="pwd-field">Confirm your password:</label>
                    <input class="pwd-field" type="password" name="pwd-2" placeholder="Re-type Password" required>
                    <p class="pwd-error-message pwd-success-message txt"></p>
                </div>

                <div>
                    <button class="btm-submit-btn" type="submit">Sign Up And Start Trading!</button>
                </div>

                <p>By clicking the button, you are agreeing to our <span class="terms">Terms and Services</span></p>
            </div>

            <div id="login-redirect">
                <p>Already have an account? </p><a href="{{ url_for('main.login') }}">Login</a>
            </div>
        </form>
    </section>
</main>
{% endblock %}